import { useCallback, useEffect, useState, type FormEvent } from "react";
import { categoriesApi } from "../api/categories.api";
import { EmptyState, ErrorState, LoadingState } from "../components/ui/States";
import type { Category } from "../types/ticket";
import { ApiError } from "../api/http.client";

export function CategoriesPage() {
  const [categories, setCategories] = useState<Category[]>([]); const [editing, setEditing] = useState<Category | null>(null); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [mutating, setMutating] = useState(""); const [error, setError] = useState("");
  const load = useCallback(() => { setLoading(true); setError(""); categoriesApi.getAdminCategories().then(setCategories).catch((reason) => setError(reason instanceof Error ? reason.message : "Categories could not be loaded.")).finally(() => setLoading(false)); }, []);
  // The mock API is an external async data source; initial state already represents loading.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(load, [load]);
  const reset = () => { setEditing(null); setName(""); setDescription(""); setError(""); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!name.trim() || saving) { if (!name.trim()) setError("Category name is required."); return; } setSaving(true); setError(""); try { if (editing) await categoriesApi.updateCategory(editing.id, { name, description }); else await categoriesApi.createCategory({ name, description }); reset(); load(); } catch (reason) { setError(reason instanceof ApiError && reason.code === "CATEGORY_NAME_CONFLICT" ? "A category with this name already exists. Choose a different name." : reason instanceof Error ? reason.message : "Category could not be saved."); } finally { setSaving(false); } };
  const toggle = async (category: Category) => { const enable = category.isActive === false; if (!enable && !window.confirm(`Disable “${category.name}”? It will no longer be available for new tickets.`)) return; setMutating(category.id); setError(""); try { await categoriesApi.setCategoryActive(category.id, enable); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Category status could not be changed."); } finally { setMutating(""); } };
  return <div className="page-stack"><section className="page-intro"><h2>Categories</h2><p>Maintain active and inactive categories available to requesters and support staff.</p></section>{error && !loading && categories.length > 0 && <div className="inline-error" role="alert">{error}</div>}<div className="management-grid"><section className="panel"><div className="panel-header"><h2>All categories</h2></div>{loading ? <LoadingState /> : error && categories.length === 0 ? <ErrorState message={error} retry={load} /> : categories.length === 0 ? <EmptyState title="No categories" message="Create the first category." /> : <div className="management-list">{categories.map((category) => <article key={category.id}><div><strong>{category.name}</strong> <span className={`badge ${category.isActive === false ? "status-cancelled" : "status-resolved"}`}>{category.isActive === false ? "Inactive" : "Active"}</span><p>{category.description ?? "No description"}</p></div><div><button className="secondary-button compact" disabled={Boolean(mutating)} onClick={() => { setEditing(category); setName(category.name); setDescription(category.description ?? ""); }}>Edit</button><button className={category.isActive === false ? "secondary-button compact" : "danger-button compact"} disabled={Boolean(mutating)} onClick={() => toggle(category)}>{mutating === category.id ? "Updating…" : category.isActive === false ? "Enable" : "Disable"}</button></div></article>)}</div>}</section><form className="panel detail-section" onSubmit={submit}><h3>{editing ? "Edit category" : "Create category"}</h3><label className="field"><span>Name <b>*</b></span><input required maxLength={100} value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span>Description</span><textarea rows={4} maxLength={500} value={description} onChange={(event) => setDescription(event.target.value)} /></label><div className="form-actions inline-actions">{editing && <button type="button" className="secondary-button" disabled={saving} onClick={reset}>Cancel</button>}<button className="primary-button" disabled={saving || !name.trim()}>{saving ? "Saving…" : editing ? "Save changes" : "Create category"}</button></div></form></div></div>;
}
