import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ticketsApi } from "../api/tickets.api";
import { useAuth } from "../contexts/AuthContext";
import type { Ticket } from "../types/ticket";
import { Icon } from "../components/ui/Icon";
import { EmptyState, ErrorState, LoadingState } from "../components/ui/States";
import { PriorityBadge, StatusBadge, formatDate } from "../components/tickets/TicketUI";
import { adminApi, type AdminDashboard } from "../api/admin.api";
import type { TicketPriority, TicketStatus } from "../types/ticket";
import { useMockApi } from "../api/api.config";

const dashboardStatuses: TicketStatus[] = ["OPEN", "CLAIMED", "IN_PROGRESS", "RESOLVED", "CLOSED", "CANCELLED"];
const dashboardPriorities: TicketPriority[] = ["LOW", "MEDIUM", "HIGH", "URGENT"];

function AdminDashboardView() {
  const { user } = useAuth();
  const [data, setData] = useState<AdminDashboard | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = () => { setLoading(true); setError(""); adminApi.getDashboard().then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : "Dashboard information is temporarily unavailable.")).finally(() => setLoading(false)); };
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(load, []);
  if (loading) return <LoadingState label="Loading the admin dashboard" />;
  if (error) return <ErrorState message={error} retry={load} />;
  if (!data) return <EmptyState title="No dashboard data" message="Dashboard statistics are not available yet." />;
  const stats = [{ label: "Total tickets", value: data.totalTickets, icon: "ticket", tone: "blue" }, { label: "Unassigned open", value: data.unassignedOpen, icon: "queue", tone: "amber" }, { label: "Active technicians", value: data.activeTechnicians, icon: "check", tone: "green" }];
  return <div className="page-stack"><section className="page-intro split"><div><span className="kicker">{new Intl.DateTimeFormat("en-US", { weekday: "long", month: "long", day: "numeric" }).format(new Date())}</span><h2>Good {new Date().getHours() < 12 ? "morning" : "afternoon"}, {user?.name.split(" ")[0]}</h2><p>Monitor service demand, assignment coverage, and technician workload.</p></div></section><section className="stat-grid" aria-label="Admin summary">{stats.map((item) => <article className="stat-card" key={item.label}><span className={`stat-icon ${item.tone}`}><Icon name={item.icon} /></span><div><strong>{item.value}</strong><span>{item.label}</span></div></article>)}</section><div className="management-grid"><section className="panel detail-section"><h3>Tickets by status</h3><div className="distribution-list">{dashboardStatuses.map((status) => <div key={status}><span>{status.replaceAll("_", " ")}</span><strong>{data.ticketsByStatus[status] ?? 0}</strong></div>)}</div></section><section className="panel detail-section"><h3>Tickets by priority</h3><div className="distribution-list">{dashboardPriorities.map((priority) => <div key={priority}><span>{priority}</span><strong>{data.ticketsByPriority[priority] ?? 0}</strong></div>)}</div></section></div><section className="panel"><div className="panel-header"><div><h2>Technician workload</h2><p>Active claimed and in-progress tickets by technician.</p></div></div>{data.technicianWorkload.length === 0 ? <EmptyState title="No active workload" message="No technicians currently have active tickets." /> : <div className="management-list">{data.technicianWorkload.map((item) => <article key={item.technicianId}><div><strong>{item.displayName}</strong><p>{item.isActive ? "Active technician" : "Inactive technician"}</p></div><span className="badge status-claimed">{item.activeTickets} active</span></article>)}</div>}</section><section className="panel"><div className="panel-header"><div><h2>Recent tickets</h2><p>Latest requests across the service desk.</p></div><Link className="text-link" to="/admin/tickets">View all <Icon name="arrow" /></Link></div>{data.recentTickets.length === 0 ? <EmptyState title="No tickets yet" message="Recent tickets will appear here." /> : <div className="ticket-list">{data.recentTickets.map((ticket) => <Link className="ticket-row" to={`/tickets/${ticket.id}`} key={ticket.id}><div className="ticket-title-cell"><span className="ticket-icon"><Icon name="ticket" /></span><div><span className="ticket-number">{ticket.ticketNumber}</span><strong>{ticket.title}</strong><small>{ticket.creator.displayName} · {formatDate(ticket.createdAt)}</small></div></div><PriorityBadge priority={ticket.priority} /><StatusBadge status={ticket.status} /><Icon className="row-chevron" name="chevron" /></Link>)}</div>}</section></div>;
}

export function DashboardPage() {
  const { user } = useAuth();
  if (user?.role === "ADMIN" && !useMockApi) return <AdminDashboardView />;
  return <RoleDashboard />;
}

function RoleDashboard() {
  const { user } = useAuth(); const [tickets, setTickets] = useState<Ticket[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = () => { if (!user) return; setLoading(true); setError(""); const request = user.role === "TECHNICIAN" ? Promise.all([ticketsApi.getTicketQueue(), ticketsApi.getAssignedTickets(user.id, {})]).then(([queue, assigned]) => [...queue, ...assigned]) : user.role === "ADMIN" ? ticketsApi.getAllTickets() : ticketsApi.getMyTickets(user.id); request.then(setTickets).catch(() => setError("Ticket information is temporarily unavailable.")).finally(() => setLoading(false)); };
  // The mock API is an external async data source; initial state already represents loading.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(load, [user]);
  if (loading) return <LoadingState label="Loading your dashboard" />; if (error) return <ErrorState message={error} retry={load} />;
  const isRequester = Boolean(user && ["STUDENT", "FACULTY"].includes(user.role));
  const isTech = user?.role === "TECHNICIAN"; const isAdmin = user?.role === "ADMIN"; const today = new Date().toDateString();
  const counts = isTech ? [{ label: "Open queue", value: tickets.filter((t) => t.status === "OPEN" && !t.assignedTechnician).length, icon: "queue", tone: "blue" }, { label: "My assigned", value: tickets.filter((t) => t.assignedTechnician?.id === user?.id).length, icon: "ticket", tone: "slate" }, { label: "In progress", value: tickets.filter((t) => t.assignedTechnician?.id === user?.id && t.status === "IN_PROGRESS").length, icon: "clock", tone: "amber" }, { label: "Resolved today", value: tickets.filter((t) => t.status === "RESOLVED" && new Date(t.updatedAt).toDateString() === today).length, icon: "check", tone: "green" }] : isAdmin ? [{ label: "Open tickets", value: tickets.filter((t) => t.status === "OPEN").length, icon: "ticket", tone: "blue" }, { label: "In progress", value: tickets.filter((t) => t.status === "IN_PROGRESS").length, icon: "clock", tone: "amber" }, { label: "Urgent", value: tickets.filter((t) => t.priority === "URGENT").length, icon: "alert", tone: "slate" }, { label: "Resolved today", value: tickets.filter((t) => t.status === "RESOLVED" && new Date(t.updatedAt).toDateString() === today).length, icon: "check", tone: "green" }] : [{ label: "Open tickets", value: tickets.filter((t) => t.status === "OPEN").length, icon: "ticket", tone: "blue" }, { label: "In progress", value: tickets.filter((t) => ["CLAIMED", "IN_PROGRESS"].includes(t.status)).length, icon: "clock", tone: "amber" }, { label: "Resolved", value: tickets.filter((t) => ["RESOLVED", "CLOSED"].includes(t.status)).length, icon: "check", tone: "green" }, { label: "Total tickets", value: tickets.length, icon: "queue", tone: "slate" }];
  const attention = isTech ? tickets.filter((ticket) => (ticket.status === "OPEN" && !ticket.assignedTechnician) || (ticket.assignedTechnician?.id === user?.id && ["CLAIMED", "IN_PROGRESS"].includes(ticket.status))) : tickets; const allLink = isAdmin ? "/admin/tickets" : isTech ? "/queue" : "/tickets";
  return <div className="page-stack"><section className="page-intro split"><div><span className="kicker">{new Intl.DateTimeFormat("en-US", { weekday: "long", month: "long", day: "numeric" }).format(new Date())}</span><h2>Good {new Date().getHours() < 12 ? "morning" : "afternoon"}, {user?.name.split(" ")[0]}</h2><p>{isRequester ? "Here’s what’s happening with your IT support requests." : isTech ? "Review the queue and tickets that need your attention." : "Monitor service demand, priority, and assignment workload."}</p></div>{isRequester && <Link className="primary-button" to="/tickets/new"><Icon name="plus" />Create ticket</Link>}</section><section className="stat-grid" aria-label="Ticket summary">{counts.map((item) => <article className="stat-card" key={item.label}><span className={`stat-icon ${item.tone}`}><Icon name={item.icon} /></span><div><strong>{item.value}</strong><span>{item.label}</span></div></article>)}</section><section className="panel"><div className="panel-header"><div><h2>{isTech ? "Needs attention" : "Recent tickets"}</h2><p>{isTech ? "Available queue items and active assigned work." : isAdmin ? "Latest requests across the service desk." : "Your latest support requests and their status."}</p></div><Link className="text-link" to={allLink}>View all <Icon name="arrow" /></Link></div>{attention.length === 0 ? <EmptyState title="Nothing needs attention" message={isRequester ? "When you submit a request, it will appear here." : "There are no matching active tickets right now."} action={isRequester ? <Link className="primary-button" to="/tickets/new">Create your first ticket</Link> : undefined} /> : <div className="ticket-list">{attention.slice(0, 5).map((ticket) => <Link className="ticket-row" to={`/tickets/${ticket.id}`} key={ticket.id}><div className="ticket-title-cell"><span className="ticket-icon"><Icon name="ticket" /></span><div><span className="ticket-number">{ticket.ticketNumber}</span><strong>{ticket.title}</strong><small>{ticket.category.name} · {formatDate(ticket.createdAt)}</small></div></div><PriorityBadge priority={ticket.priority} /><StatusBadge status={ticket.status} /><Icon className="row-chevron" name="chevron" /></Link>)}</div>}</section>{isAdmin && <section className="panel detail-section"><h3>Ticket distribution</h3><div className="distribution-list">{Array.from(new Set(tickets.map((ticket) => ticket.category.name))).map((name) => <div key={name}><span>{name}</span><strong>{tickets.filter((ticket) => ticket.category.name === name).length}</strong></div>)}</div></section>}</div>;
}
