import { useCallback, useEffect, useState } from "react";
import { usersApi } from "../api/users.api";
import { ApiError } from "../api/http.client";
import { EmptyState, ErrorState, LoadingState } from "../components/ui/States";
import { Initials, humanize } from "../components/tickets/TicketUI";
import { useAuth } from "../contexts/AuthContext";
import type { User, UserRole } from "../types/user";

const roles: UserRole[] = ["STUDENT", "FACULTY", "TECHNICIAN", "ADMIN"];
const conflictMessage = (reason: unknown) => {
  if (reason instanceof ApiError && reason.code === "SELF_LOCKOUT_PROTECTED") return "You cannot deactivate or demote your own administrator account.";
  if (reason instanceof ApiError && reason.code === "TECHNICIAN_HAS_ACTIVE_TICKETS") return "Reassign this technician’s active tickets before changing their role or status.";
  return reason instanceof Error ? reason.message : "The user could not be updated.";
};

export function UsersPage() {
  const { user: currentUser } = useAuth(); const [users, setUsers] = useState<User[]>([]); const [search, setSearch] = useState(""); const [role, setRole] = useState<UserRole | "ALL">("ALL"); const [active, setActive] = useState<"ALL" | "true" | "false">("ALL"); const [loading, setLoading] = useState(true); const [pending, setPending] = useState(""); const [error, setError] = useState("");
  const load = useCallback(() => { setLoading(true); setError(""); usersApi.getUsers({ search, role, active: active === "ALL" ? "ALL" : active === "true" }).then(setUsers).catch((reason) => setError(reason instanceof Error ? reason.message : "Users could not be loaded.")).finally(() => setLoading(false)); }, [search, role, active]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(load, [load]);
  const update = async (item: User, input: { role?: UserRole; isActive?: boolean }) => { if (pending) return; const removesTechnician = item.role === "TECHNICIAN" && (input.isActive === false || (input.role !== undefined && input.role !== "TECHNICIAN")); if ((input.isActive === false || removesTechnician) && !window.confirm(removesTechnician ? `Remove technician access for ${item.name}? Active tickets must be reassigned first.` : `Deactivate ${item.name}’s HelpDesk access?`)) return; setPending(item.id); setError(""); try { await usersApi.updateUser(item.id, input); load(); } catch (reason) { setError(conflictMessage(reason)); } finally { setPending(""); } };
  const roleControl = (item: User) => <label><span className="sr-only">Role for {item.name}</span><select aria-label={`Role for ${item.name}`} value={item.role} disabled={pending === item.id} onChange={(event) => update(item, { role: event.target.value as UserRole })}>{roles.map((itemRole) => <option value={itemRole} key={itemRole}>{humanize(itemRole)}</option>)}</select></label>;
  const accessControl = (item: User) => <button className="secondary-button compact" disabled={pending === item.id} onClick={() => update(item, { isActive: item.isActive === false })}>{pending === item.id ? "Updating…" : item.isActive === false ? "Activate" : "Deactivate"}</button>;
  return <div className="page-stack"><section className="page-intro"><h2>Users / Technicians</h2><p>Manage internal HelpDesk roles and application access. These changes do not modify Microsoft directory accounts.</p></section>{error && users.length > 0 && <div className="inline-error" role="alert">{error}</div>}<section className="panel filter-panel"><div className="filter-bar users-filter"><label className="search-field"><span className="sr-only">Search users</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name or email" /></label><label><span className="sr-only">Role</span><select value={role} onChange={(event) => setRole(event.target.value as UserRole | "ALL")}><option value="ALL">All roles</option>{roles.map((item) => <option key={item} value={item}>{humanize(item)}</option>)}</select></label><label><span className="sr-only">Active status</span><select value={active} onChange={(event) => setActive(event.target.value as typeof active)}><option value="ALL">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></label></div>{loading ? <LoadingState label="Loading users" /> : error && users.length === 0 ? <ErrorState message={error} retry={load} /> : users.length === 0 ? <EmptyState title="No users found" message="Try changing the user filters." /> : <><div className="table-wrap"><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th><th>Application access</th></tr></thead><tbody>{users.map((item) => <tr key={item.id}><td><strong>{item.name}</strong>{item.id === currentUser?.id && <small className="current-user-label">You</small>}</td><td>{item.email}</td><td>{roleControl(item)}</td><td><span className={`badge ${item.isActive === false ? "status-cancelled" : "status-resolved"}`}>{item.isActive === false ? "Inactive" : "Active"}</span></td><td>{accessControl(item)}</td></tr>)}</tbody></table></div><div className="mobile-user-cards">{users.map((item) => <article key={item.id}><div className="mobile-user-heading"><Initials name={item.name} /><div><strong>{item.name}</strong><span>{item.email}</span></div><span className={`badge ${item.isActive === false ? "status-cancelled" : "status-resolved"}`}>{item.isActive === false ? "Inactive" : "Active"}</span></div><div className="mobile-user-actions">{roleControl(item)}{accessControl(item)}</div></article>)}</div></>}</section></div>;
}
