import { useRef, useState, type ChangeEvent } from "react";
import { attachmentsApi, attachmentErrorMessage, validateAttachmentFiles } from "../../api/attachments.api";
import type { Attachment, Ticket } from "../../types/ticket";
import type { User } from "../../types/user";
import { Icon } from "../ui/Icon";
import { formatDate } from "./TicketUI";

const activeStatuses = ["OPEN", "CLAIMED", "IN_PROGRESS"];
const formatSize = (bytes: number) => bytes >= 1024 * 1024 ? `${(bytes / (1024 * 1024)).toFixed(1)} MB` : `${Math.max(1, Math.round(bytes / 1024))} KB`;
const fileKind = (mimeType: string) => mimeType === "application/pdf" ? "PDF" : mimeType === "text/plain" ? "TXT" : mimeType.split("/")[1]?.toUpperCase() || "FILE";

export function AttachmentPanel({ ticket, user, onChange }: { ticket: Ticket; user: User | null; onChange: (attachments: Attachment[]) => void }) {
  const inputRef = useRef<HTMLInputElement>(null); const [uploading, setUploading] = useState(false); const [opening, setOpening] = useState(""); const [deleting, setDeleting] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const active = activeStatuses.includes(ticket.status); const assignedToMe = ticket.assignedTechnician?.id === user?.id;
  const canUpload = Boolean(user && active && (["STUDENT", "FACULTY"].includes(user.role) || user.role === "ADMIN" || (user.role === "TECHNICIAN" && assignedToMe)));
  const canDelete = (attachment: Attachment) => Boolean(user && (user.role === "ADMIN" || (attachment.uploadedBy?.id === user.id && ((["STUDENT", "FACULTY"].includes(user.role) && ticket.status === "OPEN") || (user.role === "TECHNICIAN" && active && assignedToMe)))));
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files ?? []); event.target.value = ""; if (!user || files.length === 0 || uploading) return; const validation = validateAttachmentFiles(files); if (validation) { setError(validation); return; } setUploading(true); setError(""); setSuccess(""); try { const uploaded = await attachmentsApi.uploadAttachments(ticket.id, files, undefined, user); onChange([...ticket.attachments, ...uploaded]); setSuccess("Upload complete."); } catch (reason) { setError(attachmentErrorMessage(reason)); } finally { setUploading(false); } };
  const open = async (attachment: Attachment) => { if (opening) return; const previewWindow = window.open("about:blank", "_blank"); if (previewWindow) previewWindow.opener = null; setOpening(attachment.id); setError(""); try { const { url } = await attachmentsApi.getAttachmentUrl(ticket.id, attachment.id); if (previewWindow) previewWindow.location.replace(url); else { const link = document.createElement("a"); link.href = url; link.target = "_blank"; link.rel = "noopener noreferrer"; link.click(); } } catch (reason) { previewWindow?.close(); setError(attachmentErrorMessage(reason)); } finally { setOpening(""); } };
  const remove = async (attachment: Attachment) => { if (deleting || !window.confirm(`Remove “${attachment.fileName}” from this ticket?`)) return; setDeleting(attachment.id); setError(""); setSuccess(""); try { await attachmentsApi.deleteAttachment(ticket.id, attachment.id); onChange(ticket.attachments.filter((item) => item.id !== attachment.id)); setSuccess("Attachment removed."); } catch (reason) { setError(attachmentErrorMessage(reason)); } finally { setDeleting(""); } };
  return <section className="panel detail-section"><div className="section-title"><div><h3>Attachments</h3><p>Files shared with this ticket are private.</p></div><span>{ticket.attachments.length}</span></div>{error && <div className="inline-error attachment-feedback" role="alert"><Icon name="alert" />{error}</div>}{success && <div className="success-banner attachment-feedback" role="status"><Icon name="check" />{success}</div>}{ticket.attachments.length === 0 ? <p className="muted empty-copy">No attachments have been added to this ticket.</p> : <div className="attachment-list">{ticket.attachments.map((attachment) => <article className="attachment-row" key={attachment.id}><Icon name="file" /><div><strong>{attachment.fileName}</strong><small>{fileKind(attachment.fileType)} · {formatSize(attachment.sizeBytes)}</small><small>Uploaded by {attachment.uploadedBy?.name ?? "HelpDesk user"} · {formatDate(attachment.uploadedAt, true)}</small></div><div className="attachment-actions"><button className="secondary-button compact" type="button" disabled={opening === attachment.id} onClick={() => open(attachment)}>{opening === attachment.id ? "Opening…" : "View / download"}</button>{canDelete(attachment) && <button className="danger-button compact" type="button" disabled={deleting === attachment.id} onClick={() => remove(attachment)}>{deleting === attachment.id ? "Removing…" : "Remove"}</button>}</div></article>)}</div>}{canUpload && <div className="attachment-upload"><input ref={inputRef} className="sr-only" id={`attachment-upload-${ticket.id}`} aria-label="Choose attachments to upload" type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,.jpg,.jpeg,.png,.webp,.pdf,.txt" onChange={upload} /><button className="secondary-button" type="button" disabled={uploading} onClick={() => inputRef.current?.click()}><Icon name="clip" />{uploading ? "Uploading attachments…" : "Add attachments"}</button><small>Up to 5 files, 13 MB each.</small></div>}</section>;
}
